[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"

$accCommand = Get-Command acc.ps1, acc.cmd, acc -ErrorAction SilentlyContinue | Select-Object -First 1
if ($null -eq $accCommand) {
    throw "acc not found. Run setup-atcoder.ps1 first, then restart PowerShell."
}

$accPath = $accCommand.Source
$configDirectory = ((& $accPath config-dir) | Select-Object -Last 1).Trim()
if ([string]::IsNullOrWhiteSpace($configDirectory)) {
    throw "Failed to detect the atcoder-cli config directory."
}

Write-Host "Copy REVEL_SESSION from the browser developer tools." -ForegroundColor Cyan
Write-Host "The pasted value will not be displayed." -ForegroundColor DarkGray
$secureValue = Read-Host "REVEL_SESSION value" -AsSecureString
$valuePointer = [IntPtr]::Zero
$sessionValue = $null

try {
    $valuePointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureValue)
    $sessionValue = [Runtime.InteropServices.Marshal]::PtrToStringBSTR($valuePointer).Trim().Trim('"')
    $sessionValue = $sessionValue -replace '^REVEL_SESSION=', ''

    if ([string]::IsNullOrWhiteSpace($sessionValue)) {
        throw "REVEL_SESSION is empty."
    }

    $sessionData = [ordered]@{
        cookies = @(
            "REVEL_FLASH="
            "REVEL_SESSION=$sessionValue"
        )
    }
    $sessionJson = $sessionData | ConvertTo-Json -Depth 3
    $sessionPath = Join-Path $configDirectory "session.json"
    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($sessionPath, $sessionJson, $utf8)

    # atcoder-cli and online-judge-tools keep separate cookie stores.  During a
    # contest, AtCoder returns 404 for task pages unless oj has this cookie too.
    $ojCookieDirectory = Join-Path $env:LOCALAPPDATA "online-judge-tools\online-judge-tools"
    $ojCookiePath = Join-Path $ojCookieDirectory "cookie.jar"
    New-Item -ItemType Directory -Path $ojCookieDirectory -Force | Out-Null
    $expires = [DateTime]::UtcNow.AddYears(1).ToString("ddd, dd-MMM-yyyy HH:mm:ss 'GMT'", [Globalization.CultureInfo]::InvariantCulture)
    $cookieJar = @(
        "#LWP-Cookies-2.0"
        "# Generated by set-acc-session.ps1"
        "Set-Cookie3: REVEL_SESSION=$sessionValue; path=`"/`"; domain=`"atcoder.jp`"; path_spec; secure; expires=`"$expires`"; version=0"
        ""
    ) -join "`n"
    [System.IO.File]::WriteAllText($ojCookiePath, $cookieJar, $utf8)
}
finally {
    if ($valuePointer -ne [IntPtr]::Zero) {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($valuePointer)
    }
    $sessionValue = $null
    $secureValue = $null
}

$sessionStatus = ((& $accPath session) -join "`n").Trim()
if ($sessionStatus -notmatch '(?m)^OK$') {
    throw "acc could not verify the session. Log in again in the browser, copy a fresh REVEL_SESSION value, and retry."
}

Write-Host "[AtCoder] The login cookie was registered for acc and oj." -ForegroundColor Green
